<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>02825d9f-ae35-42a0-9863-76231e7fc289</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SendGrid" Version="9.29.3" />
  </ItemGroup>

</Project>
